#pragma once

#include "../sensors/calib.h"
#include "../types/types.h"

// LittleFS / flash storage for calibration, config, and data logging
//
// Magnetometer calibration file layout:
//   /mag_base.json   — baseline (off-scooter) calibration: M_base + b_base
//                            Generated by Python ellipsoid fit, uploaded by user.
//   /mag_mount.json  — mounted (on-scooter) correction: M_mount + b_mount
//                            Generated by Python from mounted cal samples, uploaded by user.
//   /mag_cal.json    — legacy single-stage hard-iron+soft-iron file.
//                            Read on boot as fallback if mag_base.json is absent; never written.
//
// Two-stage transform chain:
//   corrected = M_mount * (M_base * (raw - b_base) - b_mount)
//
// On boot (loadMagCalibrationChain):
//   Both files present → full chain
//   Base only          → M_base/b_base only (M_mount = identity, b_mount = 0)
//   Neither            → try legacy mag_cal.json; uncalibrated if also absent

namespace storage {

// File paths
static constexpr const char* MAG_BASE_FILE   = "/mag_base.json";
static constexpr const char* MAG_MOUNT_FILE  = "/mag_mount.json";
static constexpr const char* MAG_LEGACY_FILE = "/mag_cal.json";

// ---- Single-stage mag cal (legacy path) -----------------------------------
bool saveMagCalibration(const char* filename, const MagCalib& cal);
bool loadMagCalibration(const char* filename, MagCalib& cal);

// ---- Two-stage mag cal chain ----------------------------------------------
// Load whichever combination of base/mount files is present.
// Returns the effective single MagCalib that represents the full chain,
// and populates hasBase/hasMount so caller can log which files were loaded.
// The effective cal encodes:  corrected = M_eff * (raw - b_eff)
// where M_eff = M_mount * M_base  and  b_eff = b_base + M_base_inv * b_mount
// (pre-composed so the rest of the code only needs one MagCalib).
bool loadMagCalibrationChain(MagCalib& effectiveCal, bool& hasBase, bool& hasMount);

// ---- Calib3 (gyro / accel) ------------------------------------------------
bool saveCalib3(const char* filename, const Calib3& cal);
bool loadCalib3(const char* filename, Calib3& cal);

}  // namespace storage
