#!/usr/bin/env python3
"""Convert a PNG to a monochrome 1bpp C bitmap header for Adafruit GFX drawBitmap.

Pixels with luma >= threshold become foreground (bit=1); below become background (bit=0).
Bits are packed MSB-first within each byte; each row is padded to a full byte.

Usage:
  python tools/png_to_bitmap.py <input.png> [output.h] [threshold 0-255]

Defaults: output = <input>_bitmap.h, threshold = 128

Example:
  python tools/png_to_bitmap.py images/logo-image-w-text-inverted-small.png \\
      src/drivers/logo_bitmap.h 128
"""
import sys
from PIL import Image


def convert(img_path, out_path, var_name='logo', threshold=128):
    img = Image.open(img_path).convert('L')
    w, h = img.size
    px = img.load()
    print(f"  {w}x{h} px, threshold={threshold}")

    row_bytes = (w + 7) // 8
    data = []
    for row in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                col = bx * 8 + bit
                if col < w and px[col, row] >= threshold:
                    byte |= 1 << (7 - bit)
            data.append(byte)

    with open(out_path, 'w') as f:
        f.write('// Auto-generated by tools/png_to_bitmap.py — DO NOT EDIT\n')
        f.write('// Regenerate: python tools/png_to_bitmap.py '
                'images/logo-image-w-text-inverted-small.png src/drivers/logo_bitmap.h\n')
        f.write('// On ESP32, const arrays are already placed in flash (.rodata);\n')
        f.write('// PROGMEM is intentionally omitted to avoid header-ordering issues.\n')
        f.write('#pragma once\n\n')
        f.write(f'static constexpr int16_t LOGO_W = {w};\n')
        f.write(f'static constexpr int16_t LOGO_H = {h};\n\n')
        f.write(f'static const uint8_t {var_name}_bitmap[] = {{\n')
        for i, b in enumerate(data):
            if i % 16 == 0:
                f.write('  ')
            f.write(f'0x{b:02X}')
            if i < len(data) - 1:
                f.write(',')
            if (i + 1) % 16 == 0 or i == len(data) - 1:
                f.write('\n')
        f.write('};\n')

    total_bytes = len(data)
    print(f"  {total_bytes} bytes -> {out_path}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    inp  = sys.argv[1]
    outp = sys.argv[2] if len(sys.argv) > 2 else inp.rsplit('.', 1)[0] + '_bitmap.h'
    thr  = int(sys.argv[3]) if len(sys.argv) > 3 else 128
    convert(inp, outp, threshold=thr)
